config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'flats#index' # rota para mostrar a lista dos flats
  get '/flats/:id', to: 'flats#show', as: :flat # rota para ver os detalhes de um flat, com um nome para identificar
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  # Cria uma constante para ser usada no método #set_flats
  FLATS_URL = 'https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json'.freeze

  # Antes de executar qualquer action deste controller, rodar o método #set_flat para achar os flats
  before_action :set_flats

  def index; end

  def show
    @flat = @flats.find { |flat| flat['id'] == params[:id].to_i }
  end

  private

  def set_flats
    @flats = JSON.parse(URI.parse(FLATS_URL).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1>Flats</h1>
  <ul class="list-group">
    <% @flats.each do |flat| %>
      <li class="list-group-item">
        <h2><%= flat["name"] %></h2>
        <p><%= flat["priceCurrency"]  %> $<%= flat["price"] %></p>
        <p><%= link_to 'See details', flat_path(flat['id']) %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/flats/show.html.erb
<div class="container">
  <%= link_to "Home", root_path, class: 'btn btn-primary' %>
  <div class="row justify-content-center">
    <div class="card mb-3 col-8">
      <img src="<%= @flat["imageUrl"] %>" alt="<%= @flat["name"] %>" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title"><%= @flat["name"] %></h5>
        <p class="card-text">$<%= @flat["price"] %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lww1925AirbnbStatic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>